services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    volumes:
      - ./api:/go/src/api
    ports:
      - 1323:1323
    links:
      - db
    tty: true
  
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: echodev
      MYSQL_USER: echo
      MYSQL_PASSWORD: echo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    